name: tcm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - pyarrow
  - scipy
  - thefuzz
  - pip:
    - datasets>=2.14
    - huggingface-hub>=0.17
    - numpy>=1.24
    - tqdm
    - typing-extensions>=4.0
    - pyyaml>=5.1
    - requests>=2.19
    - fsspec>=2023.1
    - aiohttp
    - packaging>=20.0
    - filelock
    - suffix-tree
    - just-agents-core=0.4.0